import { Grade } from "../../fsrs";
import { Knowledge, LearningAction } from "../types";

export const mockKnowledges: Knowledge[] = [
  {
    id: "k1",
    name: "Basics of React",
    question: "What is React?",
    answer: "React is a JavaScript library for building user interfaces.",
    reviewState: {
      lastReviewDate: new Date("2024-12-01"),
      nextReviewDate: new Date("2024-12-15"),
      rememberInterval: 14,
      stability: 3.5,
      difficulty: 2,
      grade: Grade.Good,
      targetRetrievability: 0.8,
    },
    learningHistory: [
      {
        id: "lh1",
        date: new Date("2024-11-01"),
        action: LearningAction.Created,
      },
      {
        id: "lh2",
        date: new Date("2024-12-01"),
        action: LearningAction.Reviewed,
        reviewState: {
          lastReviewDate: new Date("2024-12-01"),
          nextReviewDate: new Date("2024-12-15"),
          rememberInterval: 14,
          stability: 3.5,
          difficulty: 2,
          grade: Grade.Good,
          targetRetrievability: 0.8,
        },
      },
    ],
  },
  {
    id: "k2",
    name: "HTTP Methods",
    question: "What does POST do?",
    answer: "POST sends data to the server to create a resource.",
    reviewState: {
      lastReviewDate: new Date("2024-11-28"),
      nextReviewDate: new Date("2024-12-12"),
      rememberInterval: 14,
      stability: 2.8,
      difficulty: 3,
      grade: Grade.Hard,
      targetRetrievability: 0.7,
    },
    learningHistory: [
      {
        id: "lh3",
        date: new Date("2024-11-10"),
        action: LearningAction.Created,
      },
      {
        id: "lh4",
        date: new Date("2024-11-28"),
        action: LearningAction.Reviewed,
        reviewState: {
          lastReviewDate: new Date("2024-11-28"),
          nextReviewDate: new Date("2024-12-12"),
          rememberInterval: 14,
          stability: 2.8,
          difficulty: 3,
          grade: Grade.Hard,
          targetRetrievability: 0.7,
        },
      },
    ],
  },
  {
    id: "k3",
    name: "JavaScript Closures",
    question: "What is a closure?",
    answer: "A closure is a function that retains access to its lexical scope.",
    reviewState: {
      lastReviewDate: new Date("2024-12-02"),
      nextReviewDate: new Date("2024-12-16"),
      rememberInterval: 14,
      stability: 3.2,
      difficulty: 2,
      grade: Grade.Good,
      targetRetrievability: 0.85,
    },
    learningHistory: [
      {
        id: "lh5",
        date: new Date("2024-11-15"),
        action: LearningAction.Created,
      },
      {
        id: "lh6",
        date: new Date("2024-12-02"),
        action: LearningAction.Reviewed,
        reviewState: {
          lastReviewDate: new Date("2024-12-02"),
          nextReviewDate: new Date("2024-12-16"),
          rememberInterval: 14,
          stability: 3.2,
          difficulty: 2,
          grade: Grade.Good,
          targetRetrievability: 0.85,
        },
      },
    ],
  },
  {
    id: "k4",
    name: "CSS Box Model",
    question: "What are the components of the box model?",
    answer: "Content, padding, border, and margin.",
    reviewState: {
      lastReviewDate: new Date("2024-11-25"),
      nextReviewDate: new Date("2024-12-09"),
      rememberInterval: 14,
      stability: 2.9,
      difficulty: 3,
      grade: Grade.Hard,
      targetRetrievability: 0.78,
    },
    learningHistory: [
      {
        id: "lh7",
        date: new Date("2024-11-05"),
        action: LearningAction.Created,
      },
      {
        id: "lh8",
        date: new Date("2024-11-25"),
        action: LearningAction.Reviewed,
        reviewState: {
          lastReviewDate: new Date("2024-11-25"),
          nextReviewDate: new Date("2024-12-09"),
          rememberInterval: 14,
          stability: 2.9,
          difficulty: 3,
          grade: Grade.Hard,
          targetRetrievability: 0.78,
        },
      },
    ],
  },
  {
    id: "k5",
    name: "TypeScript Basics",
    question: "What is TypeScript?",
    answer: "TypeScript is a strongly typed superset of JavaScript.",
    reviewState: {
      lastReviewDate: new Date("2024-12-03"),
      nextReviewDate: new Date("2024-12-17"),
      rememberInterval: 14,
      stability: 3.6,
      difficulty: 1,
      grade: Grade.Easy,
      targetRetrievability: 0.9,
    },
    learningHistory: [
      {
        id: "lh9",
        date: new Date("2024-11-20"),
        action: LearningAction.Created,
      },
      {
        id: "lh10",
        date: new Date("2024-12-03"),
        action: LearningAction.Reviewed,
        reviewState: {
          lastReviewDate: new Date("2024-12-03"),
          nextReviewDate: new Date("2024-12-17"),
          rememberInterval: 14,
          stability: 3.6,
          difficulty: 1,
          grade: Grade.Easy,
          targetRetrievability: 0.9,
        },
      },
    ],
  },
  {
    id: "k6",
    name: "REST API",
    question: "What does REST stand for?",
    answer: "Representational State Transfer.",
    reviewState: {
      lastReviewDate: new Date("2024-11-30"),
      nextReviewDate: new Date("2024-12-14"),
      rememberInterval: 14,
      stability: 3,
      difficulty: 2,
      grade: Grade.Good,
      targetRetrievability: 0.8,
    },
    learningHistory: [
      {
        id: "lh11",
        date: new Date("2024-11-10"),
        action: LearningAction.Created,
      },
      {
        id: "lh12",
        date: new Date("2024-11-30"),
        action: LearningAction.Reviewed,
        reviewState: {
          lastReviewDate: new Date("2024-11-30"),
          nextReviewDate: new Date("2024-12-14"),
          rememberInterval: 14,
          stability: 3,
          difficulty: 2,
          grade: Grade.Good,
          targetRetrievability: 0.8,
        },
      },
    ],
  },
  {
    id: "k7",
    name: "Git Basics",
    question: "What does `git commit` do?",
    answer: "It records changes to the repository.",
    reviewState: {
      lastReviewDate: new Date("2024-12-04"),
      nextReviewDate: new Date("2024-12-18"),
      rememberInterval: 14,
      stability: 3.4,
      difficulty: 2,
      grade: Grade.Good,
      targetRetrievability: 0.83,
    },
    learningHistory: [
      {
        id: "lh13",
        date: new Date("2024-11-15"),
        action: LearningAction.Created,
      },
      {
        id: "lh14",
        date: new Date("2024-12-04"),
        action: LearningAction.Reviewed,
        reviewState: {
          lastReviewDate: new Date("2024-12-04"),
          nextReviewDate: new Date("2024-12-18"),
          rememberInterval: 14,
          stability: 3.4,
          difficulty: 2,
          grade: Grade.Good,
          targetRetrievability: 0.83,
        },
      },
    ],
  },
  {
    id: "k8",
    name: "Node.js",
    question: "What is Node.js used for?",
    answer: "Node.js is used to run JavaScript on the server.",
    reviewState: {
      lastReviewDate: new Date("2024-11-29"),
      nextReviewDate: new Date("2024-12-13"),
      rememberInterval: 14,
      stability: 3.1,
      difficulty: 2,
      grade: Grade.Good,
      targetRetrievability: 0.82,
    },
    learningHistory: [
      {
        id: "lh15",
        date: new Date("2024-11-09"),
        action: LearningAction.Created,
      },
      {
        id: "lh16",
        date: new Date("2024-11-29"),
        action: LearningAction.Reviewed,
        reviewState: {
          lastReviewDate: new Date("2024-11-29"),
          nextReviewDate: new Date("2024-12-13"),
          rememberInterval: 14,
          stability: 3.1,
          difficulty: 2,
          grade: Grade.Good,
          targetRetrievability: 0.82,
        },
      },
    ],
  },
  {
    id: "k9",
    name: "React State",
    question: "What is the useState hook?",
    answer: "It allows functional components to have state.",
    reviewState: {
      lastReviewDate: new Date("2024-12-05"),
      nextReviewDate: new Date("2024-12-19"),
      rememberInterval: 14,
      stability: 3.3,
      difficulty: 2,
      grade: Grade.Good,
      targetRetrievability: 0.84,
    },
    learningHistory: [
      {
        id: "lh17",
        date: new Date("2024-11-20"),
        action: LearningAction.Created,
      },
      {
        id: "lh18",
        date: new Date("2024-12-05"),
        action: LearningAction.Reviewed,
        reviewState: {
          lastReviewDate: new Date("2024-12-05"),
          nextReviewDate: new Date("2024-12-19"),
          rememberInterval: 14,
          stability: 3.3,
          difficulty: 2,
          grade: Grade.Good,
          targetRetrievability: 0.84,
        },
      },
    ],
  },
  {
    id: "k10",
    name: "Database Basics",
    question: "What is a primary key?",
    answer: "A primary key uniquely identifies a row in a table.",
    reviewState: {
      lastReviewDate: new Date("2024-12-06"),
      nextReviewDate: new Date("2024-12-20"),
      rememberInterval: 14,
      stability: 3.4,
      difficulty: 1,
      grade: Grade.Easy,
      targetRetrievability: 0.88,
    },
    learningHistory: [
      {
        id: "lh19",
        date: new Date("2024-11-15"),
        action: LearningAction.Created,
      },
      {
        id: "lh20",
        date: new Date("2024-12-06"),
        action: LearningAction.Reviewed,
        reviewState: {
          lastReviewDate: new Date("2024-12-06"),
          nextReviewDate: new Date("2024-12-20"),
          rememberInterval: 14,
          stability: 3.4,
          difficulty: 1,
          grade: Grade.Easy,
          targetRetrievability: 0.88,
        },
      },
    ],
  },
];